# This docker manifesto holds the containers we want to build for the application
# There are mainly 4 containers
# a. Frontend - Has the react application
# b. backend - Go API's router using Gorrilla mux
# c. CORS - NGINX cors reverse proxy server to avoid CORS issue
# d. Mongo - NO SQL database
#   d.1 Mongo Express - UI to manage the database

version: "3.9"

services:
    examfrontend:
        container_name: exam-frontend
        image: exam-frontend
        build:
            context: ./frontend
            target: development
        volumes:
            - ./frontend/src:/examcenter/src
        networks:
            - examcenter-compose-network
        links:
            - examcenterserver
        ports:
            - 3000:3000
    examcenterserver:
        container_name: examcenter-server
        image: examcenter-server
        build:
            context: ./backend
            target: development
        volumes:
            - ./backend:/examcenterserver
        networks:
            - examcenter-compose-network
        links:
            - mongo
        ports:
            - '4000:4000'
    cors:
        build:
            context: ./backend/nginx
            dockerfile: Dockerfile
        container_name: cors
        networks:
           - examcenter-compose-network
        depends_on:
            - examcenterserver
        ports:
            - "4545:80"
    # swagger-ui:
    #     image: swaggerapi/swagger-ui
    #     ports:
    #         - 4001:4001
    #     environment:
    #         - API_URL
    #     networks:
    #         - examcenter-compose-network
    mongo:
        image: mongo:4
        volumes:
            - ./data:/data/db
        networks:
            - examcenter-compose-network
        ports:
            - '27017:27017'
    # mongo_seed:
    #     env_file:
    #         - .env
    #     container_name: mongo_seed
    #     build:
    #         context: ./mongo_seed
    #         dockerfile: Dockerfile
    #         args:
    #             - DATABASE_URI=$MONGOURI
    #     networks:
    #         - examcenter-compose-network
    #     depends_on:
    #         - mongo
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
        depends_on:
            - mongo
        networks:
            - examcenter-compose-network
        ports:
             - '8081:8081'
        volumes:
            - ./data:/data/db

networks:
  examcenter-compose-network:
    driver: bridge

