version: "3.9"

services:
    examcenterserver:
        container_name: examcenter-server
        image: examcenter-server
        build:
            context: .
            target: development
        volumes:
            - .:/examcenterserver
        networks:
            - mongo-compose-network
        links:
            - mongo
        ports:
            - '4000:4000'
    # swagger-ui:
    #     image: swaggerapi/swagger-ui
    #     ports:
    #         - 4001:4001
    #     environment:
    #         - API_URL
    #     networks:
    #         - mongo-compose-network
    mongo:
        image: mongo:4
        volumes:
            - ./data:/data/db
        networks:
            - mongo-compose-network
        ports:
            - '27017:27017'
    # mongo_seed:
    #     env_file:
    #         - .env
    #     container_name: mongo_seed
    #     build:
    #         context: ./mongo_seed
    #         dockerfile: Dockerfile
    #         args:
    #             - DATABASE_URI=$MONGOURI
    #     networks:
    #         - mongo-compose-network
    #     depends_on:
    #         - mongo
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
        depends_on:
            - mongo
        networks:
            - mongo-compose-network
        ports:
             - '8081:8081'
        volumes:
            - ./data:/data/db

networks:
  mongo-compose-network:
    driver: bridge

