name: Exam Center Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Exam Center Docker image
      run: docker build . --file ./backend/Dockerfile --tag exam-center-backend:$(date +%s)
      run: docker build . --file ./frontend/Dockerfile --tag exam-center-frontend:$(date +%s)
      run: docker build . --file ./backend/nginx/Dockerfile --tag exam-center-cors:$(date +%s)
